site_name: zgshen's wiki
theme:
    name: material
    features:
      - navigation.tabs
      - toc.follow
    palette:
      primary: white
    favicon: https://zguishen.com/favicon.ico?v=1.02
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences # (1)!
nav:
  - Home: 
    - Welcome: index.md
  - Java: 
    - 计算机基础: java/计算机基础.md