site_name: zgshen's wiki
theme:
    name: material
    features:
      - navigation.tabs
      - toc.follow
    palette:
      primary: white
    favicon: https://zguishen.com/favicon.ico?v=1.02
    font:
      text: Roboto
      code: Monaco
extra_css:
  - assets/css/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences # (1)!
nav:
  - Home: 
    - Welcome: index.md
  - Develop: 
    - Java:
      - index: develop/java/index.md
      - interview:
        - 计算机基础: develop/java/interview/计算机基础.md
        - Java 基础: develop/java/interview/Java基础.md
        - Java 内存模型和 JVM: develop/java/interview/Java内存模型和JVM.md
        - 并发和线程: develop/java/interview/并发和线程.md
        - 集合框架: develop/java/interview/集合框架.md
        - Spring: develop/java/interview/Spring.md
        - Redis: develop/java/interview/Redis.md
        - MQ: develop/java/interview/MQ.md
        - 微服务: develop/java/interview/微服务.md
        - 数据库: develop/java/interview/Database.md
        - Linux: develop/java/interview/Linux.md
        - 数据结构与算法: develop/java/interview/数据结构与算法.md
        - 设计模式: develop/java/interview/设计模式.md
        - 系统设计: develop/java/interview/系统设计.md
      - issues:
        - JDK9限制反射功能的错误解决方法: develop/java/issue/JDK9限制反射功能.md
    - Python:
      - 爬取图片例子: develop/python/爬取图片例子.md
      - Flask读取图片并返回前端: develop/python/flask读取图片.md
    - Git: 
      - git操作: develop/git/git操作.md
      - git注释规范: develop/git/git注释规范.md
      - git拉取最后一次提交版本: develop/git/拉取最后一次提交版本.md
    - Command:
      - apt 命令: develop/command/apt命令.md
      - Windows 切换远程桌面: develop/command/Windows切换远程桌面.md
      - code-server 部署: develop/command/code-server.md
      - 忘记root用户密码: develop/command/忘记root密码.md
      - Widows RDP 远程连接 Linux: develop/command/Widows远程连接Linux i3桌面.md
      - Linux磁盘相关: develop/command/Linux磁盘相关.md
      - Linux设置: develop/command/Linux设置.md
      - 快捷键杂项: develop/command/快捷键杂项.md
      - Tmux 终端管理工具: develop/command/Tmux终端管理工具.md
      - JMeter 压测工具: develop/command/JMeter.md
    - 剑指Offer:
      - 2单例: develop/剑指Offer/02-single-instance.md
      - 3数组中重复的数字: develop/剑指Offer/03-duplicate.md
      - 4二维数组的查找: develop/剑指Offer/04find-number-in-2d-array.md
    - Android:
      - SDK 安装: develop/android/SDK安装.md
  - Lang:
    - 资料: lang/资料.md
    - 介词: lang/介词.md