site_name: zgshen's wiki
theme:
    name: material
    features:
      - navigation.tabs
      - toc.follow
    palette:
      primary: white
    favicon: https://zguishen.com/favicon.ico?v=1.02
    font:
      code: Monaco
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences # (1)!
nav:
  - Home: 
    - Welcome: index.md
  - Develop: 
    - Java:
      - index: develop/java/index.md
      - interview:
        - 计算机基础: develop/java/interview/计算机基础.md
        - Java 基础: develop/java/interview/Java基础.md
        - Java内存模型和JVM: develop/java/interview/Java内存模型和JVM.md
        - 并发和线程: develop/java/interview/并发和线程.md
        - 集合框架: develop/java/interview/集合框架.md
        - Spring: develop/java/interview/Spring.md
        - Redis: develop/java/interview/Redis.md
        - MQ: develop/java/interview/MQ.md
        - 微服务: develop/java/interview/微服务.md
        - 数据库: develop/java/interview/数据库.md
        - Linux: develop/java/interview/Linux.md
        - 数据结构与算法: develop/java/interview/数据结构与算法.md
        - 设计模式: develop/java/interview/设计模式.md
        - 系统设计: develop/java/interview/系统涉及.md
    - Python:
      - 爬取图片例子: develop/python/爬取图片例子.md
      - Flask读取图片并返回前端: develop/python/flask读取图片.md
    - Git: 
      - git操作: develop/git/git操作.md
      - git注释规范: develop/git/git注释规范.md
    - Command:
      - Windows 切换远程桌面: develop/command/Windows切换远程桌面.md
      - code-server 部署: develop/command/code-server.md
  - Lang:
    - 资料: lang/资料.md
    - 介词: lang/介词.md