site_name: zgshen's wiki
theme:
    name: material
    features:
      - navigation.tabs
      - toc.follow
    palette:
      primary: white
    favicon: https://zguishen.com/favicon.ico?v=1.02
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences # (1)!
nav:
  - Home: 
    - Welcome: index.md
  - Develop: 
    - Java:
      - 计算机基础: develop/java/计算机基础.md
    - Git: 
      - git操作: develop/git/git操作.md
      - git注释规范: develop/git/git注释规范.md
  - Lang:
    - 资料: lang/资料.md
    - 介词: lang/介词.md