site_name: zguishen's wiki
theme:
    name: material
    features:
      - navigation.tabs
      - toc.follow
    palette:
      primary: indigo
    favicon: https://zguishen.com/favicon.ico?v=1.02
    font:
      text: Roboto
      code: Monaco
extra_css:
  - Assets/css/extra.css
extra_javascript:
  - Assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences # (1)!
  - pymdownx.arithmatex:
      generic: true
docs_dir: Notes