site_name: zguishen's wiki
theme:
  name: material
  features:
    - navigation.tabs
    - toc.follow
  palette:
    # primary: indigo
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: Assets/favicon.ico
  font:
    text: Roboto
    code: Monaco
extra_css:
  - Assets/css/extra.css
extra_javascript:
  - Assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences # (1)!
  - pymdownx.arithmatex:
      generic: true
docs_dir: Notes
plugins:
  - social:
      cards_layout: default/invert
      cards_layout_options:
        font_family: Noto Sans SC

